//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  F:\PHEactProject\Source\Project\UGUI\EleAutoCamUI.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: PENGHUI
//              Version: NX 9
//              Date: 02-09-2018  (Format: mm-dd-yyyy)
//              Time: 10:01 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public partial class EleAutoCamUI
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private Snap.UI.Block.Group group3;// Block type: Group
    private Snap.UI.Block.Button button05;// Block type: Button
    private Snap.UI.Block.FaceCollector face_select0;// Block type: Face Collector
    private Snap.UI.Block.FaceCollector face_select01;// Block type: Face Collector
    private Snap.UI.Block.FaceCollector face_select02;// Block type: Face Collector
    private Snap.UI.Block.Enumeration enum01;// Block type: Enumeration
    private Snap.UI.Block.Button button04;// Block type: Button
    private Snap.UI.Block.Group group1;// Block type: Group
    private Snap.UI.Block.Enumeration enum0;// Block type: Enumeration
    private Snap.UI.Block.Group group;// Block type: Group
    private Snap.UI.Block.LabelBlock label04;// Block type: Label
    private Snap.UI.Block.Separator separator02;// Block type: Separator
    private Snap.UI.Block.Toggle toggle0;// Block type: Toggle
    private Snap.UI.Block.Double double0;// Block type: Double
    private Snap.UI.Block.Toggle toggle01;// Block type: Toggle
    private Snap.UI.Block.Double double01;// Block type: Double
    private Snap.UI.Block.Toggle toggle02;// Block type: Toggle
    private Snap.UI.Block.Double double02;// Block type: Double
    private Snap.UI.Block.Separator separator01;// Block type: Separator
    private Snap.UI.Block.Enumeration enum02;// Block type: Enumeration
    private Snap.UI.Block.Enumeration enum03;// Block type: Enumeration
    private Snap.UI.Block.Double double03;// Block type: Double
    private Snap.UI.Block.Separator separator0;// Block type: Separator
    //private Snap.UI.Block.Tree tree_control0;// Block type: Tree Control
    private Snap.UI.Block.Button button0;// Block type: Button
    private Snap.UI.Block.Button button01;// Block type: Button
    private Snap.UI.Block.Button button02;// Block type: Button
    private Snap.UI.Block.Button button03;// Block type: Button
    private Snap.UI.Block.Button button06;// Block type: Button
    private Snap.UI.Block.Button button07;// Block type: Button
    private Snap.UI.Block.Button button08;// Block type: Button
    //------------------------------------------------------------------------------
    //Bit Option for Property: EntityType
    //------------------------------------------------------------------------------
    public static readonly int EntityType_AllowFaces = (1 << 4);
    public static readonly int EntityType_AllowDatums = (1 << 5);
    public static readonly int EntityType_AllowBodies = (1 << 6);
    //------------------------------------------------------------------------------
    //Bit Option for Property: FaceRules
    //------------------------------------------------------------------------------
    public static readonly int FaceRules_SingleFace = (1 << 0);
    public static readonly int FaceRules_RegionFaces = (1 << 1);
    public static readonly int FaceRules_TangentFaces = (1 << 2);
    public static readonly int FaceRules_TangentRegionFaces = (1 << 3);
    public static readonly int FaceRules_BodyFaces = (1 << 4);
    public static readonly int FaceRules_FeatureFaces = (1 << 5);
    public static readonly int FaceRules_AdjacentFaces = (1 << 6);
    public static readonly int FaceRules_ConnectedBlendFaces = (1 << 7);
    public static readonly int FaceRules_AllBlendFaces = (1 << 8);
    public static readonly int FaceRules_RibFaces = (1 << 9);
    public static readonly int FaceRules_SlotFaces = (1 << 10);
    public static readonly int FaceRules_BossandPocketFaces = (1 << 11);
    public static readonly int FaceRules_MergedRibFaces = (1 << 12);
    public static readonly int FaceRules_RegionBoundaryFaces = (1 << 13);
    public static readonly int FaceRules_FaceandAdjacentFaces = (1 << 14);

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public EleAutoCamUI()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "EleAutoCamUI.dlx";
            InitEvent(theDlxFileName, initialize_cb, (s) =>
            {
                return theDialog = theUI.CreateDialog(s);
            });
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        EleAutoCamUI theEleAutoCamUI = null;
        try
        {
            theEleAutoCamUI = new EleAutoCamUI();
            // The following method shows the dialog immediately
            theEleAutoCamUI.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if (theEleAutoCamUI != null)
                theEleAutoCamUI.Dispose();
            theEleAutoCamUI = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }

    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group3 = Snap.UI.Block.Group.GetBlock(theDialog, "group3");
            button05 = Snap.UI.Block.Button.GetBlock(theDialog, "button05");
            face_select0 = Snap.UI.Block.FaceCollector.GetBlock(theDialog, "face_select0");
            face_select01 = Snap.UI.Block.FaceCollector.GetBlock(theDialog, "face_select01");
            face_select02 = Snap.UI.Block.FaceCollector.GetBlock(theDialog, "face_select02");
            enum01 = Snap.UI.Block.Enumeration.GetBlock(theDialog, "enum01");
            button04 = Snap.UI.Block.Button.GetBlock(theDialog, "button04");
            group1 = Snap.UI.Block.Group.GetBlock(theDialog, "group1");
            enum0 = Snap.UI.Block.Enumeration.GetBlock(theDialog, "enum0");
            group = Snap.UI.Block.Group.GetBlock(theDialog, "group");
            label04 = Snap.UI.Block.LabelBlock.GetBlock(theDialog, "label04");
            separator02 = Snap.UI.Block.Separator.GetBlock(theDialog, "separator02");
            toggle0 = Snap.UI.Block.Toggle.GetBlock(theDialog, "toggle0");
            double0 = Snap.UI.Block.Double.GetBlock(theDialog, "double0");
            toggle01 = Snap.UI.Block.Toggle.GetBlock(theDialog, "toggle01");
            double01 = Snap.UI.Block.Double.GetBlock(theDialog, "double01");
            toggle02 = Snap.UI.Block.Toggle.GetBlock(theDialog, "toggle02");
            double02 = Snap.UI.Block.Double.GetBlock(theDialog, "double02");
            separator01 = Snap.UI.Block.Separator.GetBlock(theDialog, "separator01");
            enum02 = Snap.UI.Block.Enumeration.GetBlock(theDialog, "enum02");
            enum03 = Snap.UI.Block.Enumeration.GetBlock(theDialog, "enum03");
            double03 = Snap.UI.Block.Double.GetBlock(theDialog, "double03");
            separator0 = Snap.UI.Block.Separator.GetBlock(theDialog, "separator0");
            //tree_control0 = (NXOpen.BlockStyler.Tree)theDialog.TopBlock.FindBlock("tree_control0");
            button0 = Snap.UI.Block.Button.GetBlock(theDialog, "button0");
            button01 = Snap.UI.Block.Button.GetBlock(theDialog, "button01");
            button02 = Snap.UI.Block.Button.GetBlock(theDialog, "button02");
            button03 = Snap.UI.Block.Button.GetBlock(theDialog, "button03");
            button06 = Snap.UI.Block.Button.GetBlock(theDialog, "button06");
            button07 = Snap.UI.Block.Button.GetBlock(theDialog, "button07");
            button08 = Snap.UI.Block.Button.GetBlock(theDialog, "button08");
            //------------------------------------------------------------------------------
            //Registration of Treelist specific callbacks
            //------------------------------------------------------------------------------
            //tree_control0.SetOnExpandHandler(new NXOpen.BlockStyler.Tree.OnExpandCallback(OnExpandCallback));

            //tree_control0.SetOnInsertColumnHandler(new NXOpen.BlockStyler.Tree.OnInsertColumnCallback(OnInsertColumnCallback));

            //tree_control0.SetOnInsertNodeHandler(new NXOpen.BlockStyler.Tree.OnInsertNodeCallback(OnInsertNodecallback));

            //tree_control0.SetOnDeleteNodeHandler(new NXOpen.BlockStyler.Tree.OnDeleteNodeCallback(OnDeleteNodecallback));

            //tree_control0.SetOnPreSelectHandler(new NXOpen.BlockStyler.Tree.OnPreSelectCallback(OnPreSelectcallback));

            //tree_control0.SetOnSelectHandler(new NXOpen.BlockStyler.Tree.OnSelectCallback(OnSelectcallback));

            //tree_control0.SetOnStateChangeHandler(new NXOpen.BlockStyler.Tree.OnStateChangeCallback(OnStateChangecallback));

            //tree_control0.SetToolTipTextHandler(new NXOpen.BlockStyler.Tree.ToolTipTextCallback(ToolTipTextcallback));

            //tree_control0.SetColumnSortHandler(new NXOpen.BlockStyler.Tree.ColumnSortCallback(ColumnSortcallback));

            //tree_control0.SetStateIconNameHandler(new NXOpen.BlockStyler.Tree.StateIconNameCallback(StateIconNameCallback));

            //tree_control0.SetOnBeginLabelEditHandler(new NXOpen.BlockStyler.Tree.OnBeginLabelEditCallback(OnBeginLabelEditCallback));

            //tree_control0.SetOnEndLabelEditHandler(new NXOpen.BlockStyler.Tree.OnEndLabelEditCallback(OnEndLabelEditCallback));

            //tree_control0.SetOnEditOptionSelectedHandler(new NXOpen.BlockStyler.Tree.OnEditOptionSelectedCallback(OnEditOptionSelectedCallback));

            //tree_control0.SetAskEditControlHandler(new NXOpen.BlockStyler.Tree.AskEditControlCallback(AskEditControlCallback));

            //tree_control0.SetOnMenuHandler(new NXOpen.BlockStyler.Tree.OnMenuCallback(OnMenuCallback));;

            //tree_control0.SetOnMenuSelectionHandler(new NXOpen.BlockStyler.Tree.OnMenuSelectionCallback(OnMenuSelectionCallback));;

            //tree_control0.SetIsDropAllowedHandler(new NXOpen.BlockStyler.Tree.IsDropAllowedCallback(IsDropAllowedCallback));;

            //tree_control0.SetIsDragAllowedHandler(new NXOpen.BlockStyler.Tree.IsDragAllowedCallback(IsDragAllowedCallback));;

            //tree_control0.SetOnDropHandler(new NXOpen.BlockStyler.Tree.OnDropCallback(OnDropCallback));;

            //tree_control0.SetOnDropMenuHandler(new NXOpen.BlockStyler.Tree.OnDropMenuCallback(OnDropMenuCallback));

            //tree_control0.SetOnDefaultActionHandler(new NXOpen.BlockStyler.Tree.OnDefaultActionCallback(OnDefaultActionCallback));

            //------------------------------------------------------------------------------
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            //if (block == button05)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == face_select0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == face_select01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == face_select02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == enum01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button04)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == enum0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == label04)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == separator02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == toggle0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == double0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == toggle01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == double01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == toggle02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == double02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == separator01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == enum02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == enum03)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == double03)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == separator0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button0)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button01)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button02)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button03)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button06)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button07)
            //{
            //    //---------Enter your code here-----------
            //}
            //else if (block == button08)
            //{
            //    //---------Enter your code here-----------
            //}
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: filter_cb
    //------------------------------------------------------------------------------
    public int filter_cb(NXOpen.BlockStyler.UIBlock block, NXOpen.TaggedObject selectedObject)
    {
        return (NXOpen.UF.UFConstants.UF_UI_SEL_ACCEPT);
    }
    //------------------------------------------------------------------------------
    //Treelist specific callbacks
    //------------------------------------------------------------------------------
    //public void OnExpandCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}

    //public void OnInsertColumnCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public void OnInsertNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}

    //public void OnDeleteNodecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node)
    //{
    //}

    //public void OnPreSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
    //{
    //}

    //public void OnSelectcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, bool Selected)
    //{
    //}

    //public void OnStateChangecallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int State)
    //{
    //}

    //public string ToolTipTextcallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public int ColumnSortcallback(NXOpen.BlockStyler.Tree tree, int columnID, NXOpen.BlockStyler.Node node1, NXOpen.BlockStyler.Node node2)
    //{
    //}

    //public string StateIconNameCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int state)
    //{
    //}

    //public Tree.BeginLabelEditState OnBeginLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public Tree.EndLabelEditState OnEndLabelEditCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, string editedText)
    //{
    //}

    //public Tree.EditControlOption OnEditOptionSelectedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, int selectedOptionID, string selectedOptionText, Tree.ControlType type)
    //{
    //}

    //public Tree.ControlType AskEditControlCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public void OnMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public void OnMenuSelectionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int menuItemID)
    //{
    //}

    //public Node.DropType IsDropAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
    //{
    //}

    //public Node.DragType IsDragAllowedCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}

    //public bool OnDropCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node[] node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID, Node.DropType dropType, int dropMenuItemId)
    //{
    //}

    //public void OnDropMenuCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID, NXOpen.BlockStyler.Node targetNode, int targetColumnID)
    //{
    //}

    //public void OnDefaultActionCallback(NXOpen.BlockStyler.Tree tree, NXOpen.BlockStyler.Node node, int columnID)
    //{
    //}


    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

}
